name: Scrape Water Data

on:
  # รันทุกวันละครั้ง / ทุกชั่วโมง / หรือกำหนด cron ตามใจคุณ
  schedule:
    - cron: '0 * * * *'     # ตัวอย่าง: ทุกชั่วโมงตรง
  workflow_dispatch:       # เพื่อสั่งด้วยมือจาก UI ได้

jobs:
  scrape:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit results if changed
        run: |
          git config user.email "action@github.com"
          git config user.name  "GitHub Action"
          git add last_data.txt historical_log.csv
          if ! git diff --cached --quiet; then
            git commit -m "Update water data and historical log"
            git push
          else
            echo "No changes to commit."
          fi
