# .github/workflows/weather_alert.yml
name: Weather Forecast Alert

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # run every 15 minutes

permissions:
  contents: write

jobs:
  forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run forecast script
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_TARGET_ID:         ${{ secrets.LINE_TARGET_ID }}
          OPENWEATHER_API_KEY:     ${{ secrets.OPENWEATHER_API_KEY }}
        run: python weather_forecaster.py

      - name: Commit & Push State Files
        if: always()
        run: |
          git config user.email "action@github.com"
          git config user.name  "GitHub Action"

          # If missing, create each file with one newline so git records it
          [ -f last_forecast_id.txt ] || echo > last_forecast_id.txt
          [ -f last_alert_time.txt ]  || echo > last_alert_time.txt

          git add last_forecast_id.txt last_alert_time.txt

          # Only commit if there’s something new
          if ! git diff --cached --quiet; then
            git commit -m "Initialize or update weather alert state files"
            git push
          else
            echo "No changes to commit."
          fi
